mongri:
  container_name: mongri
  build: .
  dockerfile: Dockerfile
  volumes:
    - .:/app/src
  environment:
    - NODE_ENV=docker
  log_opt:
    max-size: "500k"
  ports:
    - "127.0.0.1:3000:3000"
